server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enableSelfPreservation: false  #关闭自我保护
    evictionIntervalTimerInMs: 4000 #清理间隔（单位毫秒，默认是60*1000）
    responseCacheUpdateIntervalMs: 4000 #刷新到换存间隔（单位毫秒，默认是30*1000）
